version: "3"

tasks:
  config:
    cmds:
      - cp .env.sample .env
      - cp ../app/.env.sample ../app/.env
  run:
    cmds:
      - go run ./cmd/
  test:
    cmds:
      - go test ./... -v
      - go vet ./...
  docs:
    cmds:
      - swag init -g cmd/main.go
  modernize:
    cmds:
      - go run golang.org/x/tools/go/analysis/passes/modernize/cmd/modernize@v0.39.0 -test ./...
  modernize_fix:
    cmds:
      - go run golang.org/x/tools/go/analysis/passes/modernize/cmd/modernize@v0.39.0 -fix -test ./...
